name: Download and Mirror Video

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "Lien de la video a telecharger"
        required: true
        type: string

jobs:
  download-and-mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          pip install yt-dlp
          ffmpeg -version
          yt-dlp --version

      - name: Create folders
        run: |
          mkdir -p downloads
          mkdir -p output

      - name: Download video
        run: |
          yt-dlp \
            -o "downloads/video.%(ext)s" \
            "${{ github.event.inputs.video_url }}"

      - name: List downloaded files
        run: ls -lh downloads

      - name: Mirror video with small zoom
        run: |
          INPUT_FILE=$(find downloads -type f | head -n 1)
          echo "Input file: $INPUT_FILE"

          if [ -z "$INPUT_FILE" ]; then
            echo "No downloaded video found."
            exit 1
          fi

          ffmpeg -y \
            -i "$INPUT_FILE" \
            -vf "hflip,scale=iw*1.05:ih*1.05,crop=iw/1.05:ih/1.05" \
            -c:a copy \
            output/video_mirror.mp4

      - name: List output files
        run: ls -lh output

      - name: Upload source artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-video
          path: downloads/

      - name: Upload mirrored artifact
        uses: actions/upload-artifact@v4
        with:
          name: mirrored-video
          path: output/
